node_lines:
  - node_line_name: retrieve_node_line
    nodes:
      - node_type: retrieval
        modules:
          - module_type: vectordb
            embedding_model:
              - openai_embed_3_large
          - module_type: bm25
            bm25_tokenizer: [ko_kiwi, ko_okt, ko_kkma]
          - module_type: hybrid_rrf
            weight_range: (4,80)
          - module_type: hybrid_cc
            normalize_method: [mm, tmm, z, dbsf]
            weight_range: (0.0, 1.0)
            test_weight_size: 101
        top_k: [3, 5, 10]
        strategy:
          metrics:
            [
              retrieval_f1,
              retrieval_recall,
              retrieval_precision,
              retrieval_ndcg,
              retrieval_map,
              retrieval_mrr,
            ]
