node_lines:
  - node_line_name: retrieve_node_line
    nodes:
      - node_type: retrieval
        modules:
          - module_type: vectordb
            embedding_model:
              - openai
              - openai_embed_3_small
              - upstage_embed
          - module_type: bm25
            bm25_tokenizer: [ko_kiwi, ko_okt, ko_kkma]
        top_k: [3, 5, 10, 20]
        strategy:
          metrics:
            [
              retrieval_f1,
              retrieval_recall,
              retrieval_precision,
              retrieval_ndcg,
              retrieval_map,
              retrieval_mrr,
            ]
      - node_type: passage_reranker
        modules:
          - module_type: koreranker
          - module_type: pass_reranker
          - module_type: cohere_reranker
        strategy:
          metrics: [retrieval_recall, retrieval_precision, retrieval_map]
        top_k: 5
  - node_line_name: post_retrieve_node_line
    nodes:
      - modules:
          - module_type: fstring
            prompt: "주어진 passage만을 이용하여 question에 따라 답하시오 passage: {retrieved_contents} \n\n Question: {query} \n\n Answer:"
        node_type: prompt_maker
        strategy:
          generator_modules:
            - batch: 2
              module_type: openai_llm
          metrics:
            - metric_name: rouge
            - embedding_model: openai_embed_3_small
              metric_name: sem_score
            - metric_name: g_eval
            - metric_name: bert_score
              lang: ko
      - modules:
          - batch: 2
            llm: gpt-4o-mini
            module_type: openai_llm
            temperature: [0.1, 0.56, 1.0]
        node_type: generator
        strategy:
          metrics:
            - metric_name: rouge
            - embedding_model: openai
              metric_name: sem_score
            - metric_name: g_eval
            - metric_name: bert_score
              lang: ko
